### ISSUE TITLE
PHP Session

### ISSUE THREAD

**Issue by 6Arin9** [znixbtw/panel-v2#9] opened 2021-04-20 11:19 UTC
if i ban user / add admin to user, that user have to relogin (logout and login) to get this admin / ban, i tried edit SessionController but i dont know how. please fix this :/

+ if i delete admin from user, that user can add invites, ban, add subs (all admin privileges) until logout :/

**Comment by sxck1337** [comment] 2021-04-20 11:23
Seems to be an issue from your side, maybe your webserver doesn't work with it. For me it's working perfectly fine, try to set it up locally with xampp and check if the problem is gone.

**Comment by sxck1337** [comment] 2021-04-20 11:34
yeah it's not changing it for the user in real-time, if you want this feature just change it yourself, there is no need to fix it, because it's not supposed to update the permissions for users in real-time

**Comment by sxck1337** [comment] 2021-04-20 11:35
Maybe znix will add this in future but it's not really necessary

**Comment by znixbtw** [comment] 2021-04-20 11:44
It will be fixed in the new update. Which will probably take time. Until then you to bare with it, sorry.
The fix is: Call ban's value from db in a function and read it every time page refreshes and not keep it in a session.

**Comment by 6Arin9** [comment] 2021-04-20 11:56
uh ok, can i know how i can use db in eg. session controller? (session controller bcuz in sessioncontroller are functions isAdmin, isBanned)

**Comment by znixbtw** [comment] 2021-04-20 13:34
not recommended.

but if u want to do it, 
1. require db file in it
2. extend it to the db

**Closed** 2021-05-20 17:30 UTC
